# Generated by Django 5.2.8 on 2025-11-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_image_url_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
